// Command example prints the url of an image generated by kavel.ai, with no key
// and no account.
//
//	go run github.com/hanshs474/kavel-go/example@latest "an isometric coffee shop, pastel palette"
//	go run github.com/hanshs474/kavel-go/example@latest -edit https://example.com/portrait.jpg "give him a buzz cut"
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"strings"

	kavel "github.com/hanshs474/kavel-go"
)

func main() {
	edit := flag.String("edit", "", "url of an image to edit instead of generating a new one")
	ratio := flag.String("ratio", "1:1", `aspect ratio: 1:1, 16:9, 9:16, 4:3, 3:4`)
	model := flag.String("model", "", "engine override, used only with an API key (KAVEL_API_KEY)")
	flag.Parse()

	prompt := strings.Join(flag.Args(), " ")
	if prompt == "" {
		fmt.Fprintln(os.Stderr, `usage: example [-edit URL] [-ratio 16:9] "your prompt"`)
		os.Exit(2)
	}

	ctx := context.Background()
	// An API key is read from KAVEL_API_KEY by the package itself.
	opts := kavel.Options{AspectRatio: *ratio, Model: *model}

	var (
		img kavel.Image
		err error
	)
	if *edit != "" {
		img, err = kavel.Edit(ctx, *edit, prompt, opts)
	} else {
		img, err = kavel.Generate(ctx, prompt, opts)
	}

	switch {
	case errors.Is(err, kavel.ErrQuota):
		fmt.Fprintln(os.Stderr, "the free allowance for this machine is spent for today — https://www.kavel.ai/pricing")
		os.Exit(1)
	case errors.Is(err, kavel.ErrRejected):
		fmt.Fprintln(os.Stderr, "the prompt was refused; rewording it clears this, retrying it does not")
		os.Exit(1)
	case err != nil:
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	fmt.Println(img.URL)
	if img.Watermarked {
		fmt.Fprintln(os.Stderr, "(watermarked — signing in removes it)")
	}
}
